### PR TITLE
Remove leading zeros

### PR DESCRIPTION
**Pull request by SimonRichardson**
The aim of this PR is to remove leading zeros after the country code.
We've seen a lot of issues where users don't understand that when placed
with a UI with a country code already there, they don't require any
leading zeros.

As an example:

```
 +4407481092544
```

The system at hand couldn't decipher that the user had inserted a zero
and rejected the number accordingly because of the range (length) check.

This fix removes all leading zeros after the country code, if there is
no country provided then it will not attempt to do this as the chances
are it would be wrong most of the time.

The removal of leading zeros is only on when turned on by use of a flag
on the PhoneData struct `RemoveLeadingZeros`. We've not turned this on
by default as there is a possibility that chaos could ensue, so it's
better to turn them on as we go!

### CODE REVIEW

**Comment by iceydee** [comment]
could we have `removeLeadingZeroes` as true by default - and then we can remove if there's any exceptions as we go?

**Comment by iceydee** [comment]
ie. right now you're only fixing Ireland and UK. But this problem will be there for every country, and we'll have forgotten by the next time we launch somewhere else. ;)

**Review by iceydee — CHANGES_REQUESTED** [review]
Remove leading zeroes from all countries by default. Allow for exceptions ofc.

**Comment by SimonRichardson** [comment]
Sounds dangerous to me, I'm not confident on which ones should/shouldn't work. If that's that case and we do want to do that, then we should at least check a handful of resources to verify.

**Comment by iceydee** [comment]
https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers

According to that, seems only Switzerland should have exception.

**Comment by iceydee** [comment]
Italy has for landline numbers. Seems to be the only exception.

**Review by iceydee — APPROVED** [review]

**Pull request merged**
